// com.qf.api.localc
// Naming convention: https://wiki.openoffice.org/wiki/Documentation/DevGuide/AppendixA/General_Design_Rules

module com {
    module qf {
        module api {
            module localc {
                interface XQFinance
                {
                  // Returns extension version
                  any QFVersion();
                  // Returns an EOD price for a given date
                  any QFClosingPrice( [in] string symbol, [in] string category, [in] any fordate );
                  any QFOpeningPrice( [in] string symbol, [in] string category, [in] any fordate );
                  any QFHighPrice( [in] string symbol, [in] string category, [in] any fordate );
                  any QFLowPrice( [in] string symbol, [in] string category, [in] any fordate );
                };
            };
        };
    };
};
